ALTER TABLE Exercises
    ADD COLUMN category_id INTEGER REFERENCES Categories(id),

    ALTER COLUMN name TYPE VARCHAR(100),

    ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    DROP COLUMN category;